"""Write notebooks/requirements-colab.txt: the locked versions the notebooks need.

Colab ships its own numpy/scipy/xarray. Installing only pycalphad would mix
those with pycalphad 0.11.2, so the notebooks install this pinned list instead,
taken from poetry.lock: pycalphad, numpy, scipy and everything they depend on.

Run from the repository root after changing poetry.lock:
    .venv/bin/python notebooks/export_requirements.py
"""
from __future__ import annotations

import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / 'notebooks' / 'requirements-colab.txt'
ROOTS = ['pycalphad', 'numpy', 'scipy']  # matplotlib and xarray come in through pycalphad


def closure(lock: dict) -> dict[str, str]:
    packages = {p['name'].lower(): p for p in lock['package']}
    pinned, todo = {}, list(ROOTS)
    while todo:
        name = todo.pop().lower().replace('_', '-')
        if name in pinned or name not in packages:
            continue
        package = packages[name]
        pinned[name] = package['version']
        todo.extend(package.get('dependencies', {}).keys())
    return pinned


def render() -> str:
    lock = tomllib.loads((ROOT / 'poetry.lock').read_text())
    lines = ['# Generated by notebooks/export_requirements.py from poetry.lock; do not edit.',
             '# The notebooks install this list in Colab so results match the locked run.']
    lines += [f'{name}=={version}' for name, version in sorted(closure(lock).items())]
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    OUTPUT.write_text(render())
    print(f'wrote {OUTPUT.relative_to(ROOT)}')
